name: app_ban_giay
description: Một app bán giày thoi không có gì đâu.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.1
  dio: ^5.3.3
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.4
  getwidget: ^4.0.0
  go_router: ^12.0.1
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  riverpod_annotation: ^2.2.1
  
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.2

dev_dependencies:
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.5
  build_runner: ^2.4.6
  custom_lint: ^0.5.5
  riverpod_lint: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
